micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/key-manager-grpc`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'

bcb:
  pix:
    url: 'http://localhost:8082'

ITAU_UNIBANCO_ISPB: '60701190'